notification 	 = Never
universe         = vanilla
Requirements = (Machine == "igsarfebaskoimaster")
RunAsOwner = True
executable       = step2.py
arguments        =  $(the_analysis_name)

#convert_fastaqual_fastq.py -f /home/smccalla/htcondor/GAIM_12/data/join_paired_ends/fastqjoin.join.fastq -c fastq_to_fastaqual -o /home/smccalla/htcondor/GAIM_12/data/fasta_files
#python step1.py GAIM_05*_R1_001.fastq.gz GAIM_05*_R2_001.fastq.gz GAIM_05 160408_NB501144_0002_AHMFMNBGXX Loons_Long_Tailed

stream_output = True
stream_error = True
log              = /home/smccalla/htcondor/$(sample_name)/log/step2.log
output           = /home/smccalla/htcondor/$(sample_name)/log/step2.out
error            = /home/smccalla/htcondor/$(sample_name)/log/step2.error
should_transfer_files = YES
queue      1