notification = Never
universe         = vanilla
# probably need blastn installed on each machine. double check if ok to just run local copy
Requirements = (Machine == "igsarfebaskoimaster")

executable       =/home/smccalla/htcondor/step1.py

arguments        =$(sample_name)_*R1_001.fastq.gz $(sample_name)_*R2_001.fastq.gz $(the_analysis_name) 160408_NB501144_0002_AHMFMNBGXX Loons_Long_Tailed

RunAsOwner = True
stream_output = True
stream_error = True
log              = /home/smccalla/htcondor/$(sample_name)/log/step1.log
output           = /home/smccalla/htcondor/$(sample_name)/log/step1.out
error            = /home/smccalla/htcondor/$(sample_name)/log/step1.error

#log              = /home/smccalla/htcondor/GAIM_29/log/step1.log
#output           = /home/smccalla/htcondor/GAIM_29/log/step1.out
#error            = /home/smccalla/htcondor/GAIM_29/log/step1.error



#should_transfer_files = YES
#transfer_output_files = /home/Applications/chly03/results/group_$(Process).out

#when_to_transfer_output = ON_EXIT
#transfer_output_remaps = "group_$(Process).xml = /home/Applications/chly03/results/group_$(Process).xml"
#transfer_output_remaps---> use if I want to put in to a specific directory if I don't want it to come back to my submit directory

#transfer_input_files = /home/Applications/chly03/group_$(Process).fasta
#transfer_input_files = step1.py
# call queue with the number of chunks you split the input into
queue      1
